version: '3'
services:
  croustibatch:
    build:
      context: ./raw/
    #image: nicolasmir/docker_croustibatch_1:latest
    ports:
    - "2222:2222"
    environment:
      INSIGHT_HOST: localhost
      INSIGHT_PORT: 8090
      CROUSTIBATCH_NAME: CROUSTIBATCH
    # --endpoint = ip de insight
    command:  bash -c 'python3.6 /app/crawler.py --source ${SOURCE} --i ${INPUT} --config ${CONFIG} --runtime_data ${RUNTIME} --endpoint ${ENDPOINT} -v -t'
    #command: ["tail", "-f", "/dev/null"]
    networks:
    - insight
    volumes:
    - ../download:/app/download
    - ../source:/app/source
networks:
  insight:
    external: true
