version: '3'
services:
  croustibatch:
    build:
      context: ./raw/
    #volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "22:22"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - insight
networks:
  insight:
    external: true
