version: '3'
services:
  croustibatch:
    build:
      context: ./raw/
    ports:
    - "22:22"
    environment:
      INSIGHT_HOST: locahost
      INSIGHT_PORT: 8090
      CROUSTIBATCH_NAME: CROUSTIBATCH
    networks:
    - insight
networks:
  insight:
    external: true
